### ISSUE TITLE
不支持外边缘颜色设置吗

### ISSUE THREAD

**Issue by xiaogu-space** [gavinliu/ShapedImageView#1]

**Comment by gavinliu** [comment]
对，目前只是一个很简单的版本，是为了 [Android - 实现图片圆角显示的几种方式](http://gavinliu.cn/2016/04/12/Android-%E5%AE%9E%E7%8E%B0%E5%9B%BE%E7%89%87%E5%9C%86%E8%A7%92%E6%98%BE%E7%A4%BA%E7%9A%84%E5%87%A0%E7%A7%8D%E6%96%B9%E5%BC%8F/) 这篇博客写的，用最少代码实现的最少功能。边框很好实现，我晚点再更新一下，到时候回复你。

**Comment by xiaogu-space** [comment]
好的，给力，感觉功能越少越好，多了就臃肿啦

**Comment by gavinliu** [comment]
已经加上了，可以在xml中定义 边框大小和颜色

`compile 'cn.gavinliu.android.lib:ShapedImageView:0.5'`
