### ISSUE TITLE
Manifest Merger Failed

### ISSUE THREAD

**Issue by addisonElliott** [gavinliu/ShapedImageView#10]
Hello, when importing your library into my application, I get the following error:

> Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(true) from AndroidManifest.xml:21:9-35
> 	is also present at [cn.gavinliu.android.lib:ShapedImageView:0.8.4] AndroidManifest.xml:12:9-36 value=(false).
> 	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:20:5-118:19 to override.

This is from the AndroidManifest.xml in your library have a android:allowBackup, android:supportRtl, and an android:label attributes.

These attributes should be removed so that this error goes away.

**Comment by gavinliu** [comment]
Using tools:replace in your manifest file, such as:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools">
<application tools:replace="android:allowBackup;..."

**Comment by addisonElliott** [comment]
Yes, I did use that to temporarily fix the issue, but wouldn't it be better to remove this from the AndroidManifest so that is not required for anyone using your library?

**Comment by mehranabi** [comment]
Hello, Please fix this in your library.

**Comment by gavinliu** [comment]
fixed , please try 0.8.5

```
'cn.gavinliu.android.lib:ShapedImageView:0.8.5'
```
