### ISSUE TITLE
加载网络图片  有问题

### ISSUE THREAD

**Issue by FZJL** [gavinliu/ShapedImageView#3]
第一次进入 正常 ，但是再次进去 就不正常了
http://ww3.sinaimg.cn/mw690/005SMY79gw1f5tae780jaj30k00zkwfz.jpg

第一行 的 左右两边的图片 是用  universalimageloader 加载
第三行 的 左右两边的图片 是用  Glide加载

都出现同样的问题   不知道是不是缓存的问题  请赐教

**Comment by gavinliu** [comment]
目前我在项目中就是用的 Glide 没有出现什么问题。 

你指的问题是左右两边的图片没有变成圆形？

**Comment by FZJL** [comment]
是啊   第一次进去是圆形的，但是退出之后 再进去就变成图片里面那样了

**Comment by FZJL** [comment]
我关闭网络   图片依然能加载   我想是不是 缓存的时候  缓存方式不对

 Glide.with(this).load(imageUrl1).diskCacheStrategy(DiskCacheStrategy.ALL).placeholder(R.drawable.loadinggif).into(imageView5);

**Comment by feizaojilao** [comment]
我是把 ShapedImageView 这个文件 单纯的复制到 自己的项目里，使用的

**Comment by gavinliu** [comment]
你图片链接发给我看看

**Comment by FZJL** [comment]
String imageUrl1="http://ww1.sinaimg.cn/large/610dc034jw1f5hpzuy3r7j20np0zkgpd.jpg";

**Comment by gavinliu** [comment]
``` java
Glide.with(this)
                .load("http://ww1.sinaimg.cn/large/610dc034jw1f5hpzuy3r7j20np0zkgpd.jpg")
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .centerCrop()
                .into(imageview);
```

加个  .centerCrop()

**Comment by FZJL** [comment]
多谢，在布局文件中 添加 android:scaleType="centerCrop"  就行了  universalimageloader 也一样解决了
