### ISSUE TITLE
Glide removes stroke

### ISSUE THREAD

**Issue by lukaspili** [gavinliu/ShapedImageView#7]
Loading an image with Glide into ShapedImageView seems to remove the stroke.

```
Glide.with(context)
                    .load(user.image)
                    .centerCrop()
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .into(pictureImageView)
```

**Comment by weilixing00** [comment]
i solve this question by after your code add the below 
 siv.setShapeMode(ShapedImageView.SHAPE_MODE_CIRCLE); 
now it is ok

**Comment by addisonElliott** [comment]
@lukaspili Has this issue been solved?

**Comment by lukaspili** [comment]
Old project and one time usage of this library. I don't remember anymore but I don't think so.

**Comment by gavinliu** [comment]
I can not reproduce this problem, Could you run the sample app ?

https://github.com/gavinliu/ShapedImageView/blob/master/app/src/main/java/cn/gavinliu/android/lib/shapedimageview/demo/ListActivity.java
